### ISSUE TITLE
spinkit(type = "circle_fade")

### ISSUE THREAD

**Issue by IZE85** [rsquaredacademy/standby#3]
Could it be that the spinner "circle_fade" is not working? I am using R 4.2.3. While the other spinners work without a problem, this version does not load the code. Only the "Render"-button gets loaded.

reprex:
library(shiny)
library(standby)
ui <- fluidPage(
standby::useSpinkit(), # include dependencies
fluidRow(
standby::spinkit(plotOutput("plot1"), type = "circle_fade"), # wrap output inside loader
actionButton("render", "Render")
)
)
server <- function(input, output, session) {
output$plot1 <- renderPlot({
input$render
Sys.sleep(3)
hist(mtcars$mpg)
})
}
shinyApp(ui, server)

**Comment by aravindhebbali** [comment]
Hi.. The type should be `circle-fade`. I will fix this in the documentation. 

```
library(shiny)
library(standby)
ui <- fluidPage(
  standby::useSpinkit(), # include dependencies
  fluidRow(
    standby::spinkit(plotOutput("plot1"), type = "circle-fade"), # wrap output inside loader
    actionButton("render", "Render")
  )
)
server <- function(input, output, session) {
  output$plot1 <- renderPlot({
    input$render
    Sys.sleep(3)
    hist(mtcars$mpg)
  })
}
shinyApp(ui, server)
```
